# Generated by Django 6.1.1 on 2026-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_category_alter_livro_autor_livro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nationality',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
