# Generated by Django 6.1.1 on 2026-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores_temp',
            field=models.ManyToManyField(to='biblioteca.autor'),
        ),
    ]
