# Generated by Django 6.1.1 on 2026-10-10 12:57

from django.db import migrations


def copiar_autores(apps, schema_editor):
    Livro = apps.get_model('biblioteca', 'Livro')
    for livro in Livro.objects.all().iterator():
        if livro.autor:
            livro.autores_temp.add(livro.autor)

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_livro_autores_temp'),
    ]

    operations = [
        migrations.RunPython(code=copiar_autores)
    ]
