# Generated by Django 6.1.1 on 2026-10-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_migrar_dados_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AlterField(
            model_name='livro',
            name='autores_temp',
            field=models.ManyToManyField(related_name='books', to='biblioteca.autor'),
        ),
    ]
